@startuml
!include ./style.puml

package "Course" {
    stereotype "Academic map graphical view" AS course_dependencyGraphView {
        {field} overview: I as a registrar want the system to show me a graphical view of the academic map dependencies, so that I can asses if courses depedencies are correct.
    }
    stereotype "Course dependency" AS course_dependency {
        {field} overview: I as a registrar want to register that a course depends in other courses.
    }
	course_dependency <.. course_dependencyGraphView: <<drvReqt>>
    stereotype "Course assignation" AS course_assignation {
        {field} overview: As a registrar want to set in which term a course is available.
    }
    stereotype "Course" AS course {
        {field} overview: I as a registrar want to create/update/delete courses of the Commercial Software Engineering career.
    }
	course <.. course_dependency: <<drvReqt>>
	course +-- course_assignation
}

package "Enrollment" AS pkg_enrollment {
    stereotype "Student selection" AS student_selection {
        {field} overview: I as registrar want to select a student from a list, so that him/her would be enrolled to it.
    }
    stereotype "Collect list of failed students" {
        {field} overview:
    }
    stereotype "Automatically advance students to next course" {
        {field} overview:
    }
    stereotype "Enrollment compliance" AS enrollment_compliance {
        {field} overview: Ensure student is enrolled in 3 courses, taking into account ESP
    }
    stereotype "Force enrollment" AS enrollment_forced {
        {field} overview: I as registrar want to forcibly enroll a student so that he/she can be enrolled because of a management decision.
		{field} A forced enrollment should have a justification.
		{field} Registrar should be able to select a pre-made justification.
    }
    stereotype "Notifications" AS notifications {
        {field} overview: I as registrar want to receive notifications when attempting to enroll a student and: student isn't available for timeslot, student doesn't have pre-requisite courses.
    }
    stereotype "Enrollment" AS enrollment {
        {field} overview: I as registrar want to enroll students in a class.
    }
	enrollment +-- enrollment_forced
	enrollment +-- notifications
}

package "Module report" AS module {
    stereotype "Auto student advance" AS module_autoAdvance {
        {field} overview: I as registrar want to automatically advance students
    }
    stereotype "Student list" AS module_studentView {
        {field} overview: I as registrar want a list of students in two groups, passed and failed.
    }
    stereotype "End module button" AS module_end {
        {field} overview: Press button to mark module as ended. This is the first step of new module process.
    }
    stereotype "Module student management" AS module_mgmt {
        {field} overview: I as Registrar want a view to manage the students.
    }
}

@enduml
    stereotype "" AS {
		{field} id:
        {field} overview:
    }
