@startuml
!include style.puml

title System requirements
footer SySML requirements diagram

!include student-management.puml
!include teacher-management.puml
!include courses-management.puml
!include timetable.puml
!include class.puml
!include enrollment-analysis.puml

package "Reports" {
    ' OUTPUT
    stereotype "Schedule report" AS report_sch{
        {field} overview: specific reports per term, student, proffessor, range of time
    }
    stereotype "teaching staff report" AS report_t{
        {field} overview: A report that indicates the amount of teaching staff required for next term.
    }
    stereotype "Reports generation" AS report{
        {field} overview: Registrar wants to generate informational reports so that it can share information with other actors.
    }
    report +-- report_t
    report +-- report_sch
}

package "non-functional" {
    stereotype "FERPA compliance" {
        {field} overview: When producing reports, system should comply with FERPA alignments taking into account which user is trying to access which records.
    }
    stereotype "Dark mode" {
        {field} overview: Switch to dark mode
    }
}


@enduml
    stereotype "" {
        {field} overview:
    }
