@startuml
!include ../style.puml

actor Registrar
actor "Student Services" AS SS
rectangle "Enrolled in course" as G_Enrolled <<Goal>>

package "Student" <<actorboundary>> {
' --- Main Goal related to Registrar's Services ---
rectangle "Attain career degree" as G_StudentProgress <<Goal>>
	G_StudentProgress --o G_Enrolled: decomposes into

	rectangle "Verify enrollment & access personal timetable" as T_VerifyEnrollmentTimetable <<Task>>
	rectangle "Attend to enrolled classes (group, section)" as T_AttendClasses <<Task>>

	T_VerifyEnrollmentTimetable --> G_Enrolled
	T_AttendClasses --> G_Enrolled

	rectangle "Request course withdrawal (drop/LOA)" as T_RequestWithdrawal <<Task>>
	rectangle "Request reinstatement in course" as T_RequestReinstatement <<Task>>

rectangle "Attend failed course" as G_RectifyFailures <<Goal>>
	rectangle "Identify Failed Courses from Record" as T_IdentifyFailed <<Task>>

	G_RectifyFailures --o G_Enrolled: decomposes into
	G_RectifyFailures <|-- T_IdentifyFailed: means-end

cloud "Accurate & timely timetable information" as SG_AccurateTimetable <<Softgoal>>
	T_VerifyEnrollmentTimetable ..> SG_AccurateTimetable : + (HELP)
cloud "Fast timetable generation" as SG_AccurateTimetable <<Softgoal>>
cloud "Enrollemnt flexibility" as SG_AccurateTimetable <<Softgoal>>

database "Personal academic record (grades, enrollment history)" as R_AcademicRecord <<Resource>>
	T_IdentifyFailed --> R_AcademicRecord: uses
	T_VerifyEnrollmentTimetable --> R_AcademicRecord: uses
}

database "Module timetable" as R_CourseTimetableInfo <<Resource>>
	T_AttendClasses --> R_CourseTimetableInfo: uses
	G_Enrolled <-- Registrar
	R_CourseTimetableInfo <-- Registrar

rectangle "Enrollment flexibility" as T_EnrollmentFlexibility <<Task>>
	SS --> T_EnrollmentFlexibility
	T_RequestWithdrawal --> T_EnrollmentFlexibility
	T_RequestReinstatement --> T_EnrollmentFlexibility

rectangle "Enrollment compliance" as T_EnrollmentCompliance <<Task>>
@enduml
