@startuml
!include ../style.puml

actor Registrar
actor "Student Services" AS SS
rectangle "Enrolled" as G_Enrolled <<Goal>>

package "Student" <<actorboundary>> {
	rectangle "LOA, Course drop, withdraw" as T_RequestReinstatement <<Task>>
	rectangle "Verify enrollment" as T_VerifyEnrollmentTimetable <<Task>>
	rectangle "Attend class" as T_AttendClasses <<Task>>

	T_AttendClasses --o T_VerifyEnrollmentTimetable: decomposes-into
	G_Enrolled o-- T_AttendClasses: decomposes-into

	rectangle "Repeat failed course" as G_RectifyFailures <<Task>>
	G_Enrolled o-- G_RectifyFailures: decomposes into
}

database "Module timetable" as R_CourseTimetableInfo <<Resource>>
	R_CourseTimetableInfo <-- T_VerifyEnrollmentTimetable: uses
	Registrar <-- G_Enrolled
	Registrar <-- R_CourseTimetableInfo

cloud "Enrollment flexibility" as T_EnrollmentFlexibility <<Softgoal>>
	Registrar <-- T_EnrollmentFlexibility
	T_EnrollmentFlexibility o-- T_RequestReinstatement: decomposes-into

cloud "Enrollment compliance" as T_EnrollmentCompliance <<Softgoal>>
	T_VerifyEnrollmentTimetable --o T_EnrollmentCompliance: decomposes-into
	T_EnrollmentCompliance --> SS
@enduml
