@startgantt 
language spa
header Scheduling System
title Cronograma de trabajo - Semanal
footer Diagrama Gantt
ganttscale weekly

Project starts 2025-01-06

-- Investigacion exploratoria --
[Capítulo 1: Estructura Propositiva] AS [A1] STARTS 2025-01-06
[A1] ENDS 2025-02-02

[Capítulo 2: Marco Teórico] AS [A2] STARTS AT [A1]'S END
[A2] ENDS 2025-04-14

-- Desarrollo del sistema --
[Capítulo 3: Aplicacion Práctica] AS [A3] STARTS 2025-03-10
[A3] ENDS 2025-06-07

[Fase de exploracion] AS [S-0] STARTS 2025-02-03
[S-0] ENDS 2025-03-16
then [Iteration 1: UI prototyping] AS [S-1] LASTS 14 DAYS
then [Iteration 2: Schedule generation] AS [S-2] LASTS 14 DAYS
then [Iteration 3: Data input, teaching, students] AS [S-3] LASTS 14 DAYS
then [Iteration 4: Data input, courses, excel] AS [S-4] LASTS 14 DAYS
then [Iteration 5: ML forecasting] AS [S-5] LASTS 14 DAYS
then [Iteration 6: Clash management] AS [S-6] ENDS 2025-06-07
[VERSION ALFA] AS [M-1] HAPPENS AT [S-6]'S END
[M-1] IS COLORED IN Fuchsia/FireBrick
@endgantt
