@startuml
skinparam linetype ortho

'				Entities
entity Student {
	* ID <<key>>
	--
	* full_name
	timezone
	email_address
	country
}
entity Section {
	* ID <<key>>
	--
	* alpha_num_name
 }
entity Group {
	* ID <<key>>
	--
	* alpha_num_name
 }
entity Cohort {
	* ID <<key>>
	--
	* alpha_num_name
 }
entity Term {
	* ID <<key>>
	--
	* num_name
 }
entity Teacher {
	* ID <<key>>
	--
	* full_name
 }
entity Class {
	* ID <<key>>
	--
	* title
 }
 entity Timeslot {
	* ID <<key>>
 }
entity Timetable {
	* ID <<key>>
	name
 }
 entity Day {
    * ID <<key>>
    date
 }
 entity Period {
    * ID <<key>>
	--
    * start
    * end
 }

'				Connections
Student }o--|| Section
Student }o--|| Group
Cohort }o--|| Term
Cohort ||--o{ Group

Student }|--|{ Class
Teacher ||--|{ Class
Class ||--|{ Timeslot
Timeslot ||--|{ Day
Day ||--|{ Period
Timetable ||--|{ Timeslot
@enduml
