@startuml

!include style.puml


!include actor-boundaries/registrar.puml
!include actor-boundaries/teacher.puml
!include actor-boundaries/student.puml
!include actor-boundaries/sis.puml
!include actor-boundaries/academic-coordinator.puml
!include actor-boundaries/student-services.puml
!include actor-boundaries/program-director.puml

@enduml
