@startuml
!include style.puml
skinparam linetype ortho

actor "Student Services" AS SS
actor Student
actor Registrar
actor "Academic Coordinator" AS coordinator
actor "Student Information System" AS SIS
actor Teacher

cloud "Enrollment flexibility" as SG_EnrollmentFlexibility <<Softgoal>>
	Student --> SG_EnrollmentFlexibility
	SG_EnrollmentFlexibility --> Registrar

database "Student Data" as R_StudentData <<Resource>>
	Registrar --> R_StudentData
	R_StudentData --> SIS

database "Module timetable" as R_CourseTimetableInfo <<Resource>>
	R_CourseTimetableInfo <-- Teacher
	R_CourseTimetableInfo <-- Student
	Registrar <-- R_CourseTimetableInfo

database "Student grades" as R_StudentGrades <<Resource>>
	SIS --> R_StudentGrades
	R_StudentGrades --> Teacher

database "Hired teachers\ndata" as R_HiredFacultyDB <<Resource>>
	Registrar --> R_HiredFacultyDB
	R_HiredFacultyDB --> coordinator

database "Teaching staff\nto be hired" as R_RequiredTeachers <<Resource>>
	R_RequiredTeachers <-- coordinator
	Registrar <-- R_RequiredTeachers

rectangle "Enrolled" as G_Enrolled <<Goal>>
	Student --> G_Enrolled
	G_Enrolled --> Registrar

rectangle "Hired" as G_Hired <<Goal>>
	G_Hired <-- Teacher
	coordinator <-- G_Hired

cloud "Enrollment compliance" as T_EnrollmentCompliance <<Softgoal>>
	Student --> T_EnrollmentCompliance
	T_EnrollmentCompliance --> SS

cloud "Class schedule flexibility" as SG_ClassFlexibility <<Softgoal>>
	SG_ClassFlexibility <-- Teacher
	Registrar <-- SG_ClassFlexibility

@enduml
