!theme vibrant

' Styling to approximate i* notation
skinparam backgroundColor white
skinparam defaultFont Helvetica
skinparam defaultTextAlignment center
skinparam shadowing false
skinparam wrapWidth 250

skinparam package {
    BorderColor Gray
    BackgroundColor White
    StereotypeFontColor DimGray
    FontColor Black
    stereotype<<actorboundary>> {
        BorderColor Black
        BackgroundColor LightGray
    }
}

skinparam actor {
    BorderColor Black
    BackgroundColor LightBlue
    StereotypeFontColor Black
    StereotypeFontSize 10
}

skinparam rectangle<<Goal>> {
    StereotypePosition top
    borderColor DarkGreen
    backgroundColor LightGreen
    roundCorner 25 ' Make it more oval-like
}
skinparam cloud<<Softgoal>> {
    StereotypePosition top
    borderColor Orange
    backgroundColor LightYellow
}
skinparam rectangle<<Task>> {
    StereotypePosition top
    borderColor Blue
    backgroundColor LightCyan
}
skinparam rectangle<<Resource>> {
    StereotypePosition top
    borderColor DimGray
    backgroundColor WhiteSmoke
}
skinparam database<<Resource>> {
    StereotypePosition top
    borderColor DimGray
    backgroundColor WhiteSmoke
}
